name: 'E2e Tests'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - final

jobs:
  tests:
    runs-on: ubuntu-latest
    name: 'E2e Tests'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - uses: volta-cli/action@v4
      - name: Install Dependencies
        run: pnpm install
      - name: Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_STORYBOOK }}
          configFile: '.chromatic.config.json'
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: test-results
            path: ./test-results
            retention-days: 14
  chromatic:
      name: Chromatic
      needs: tests
      if: success()
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v4
          with:
            node-version: 22.12.0
        - uses: pnpm/action-setup@v3
        - name: Install dependencies
          run: pnpm install
        - name: Download Playwright test results
          uses: actions/download-artifact@v4
          with:
            name: test-results
            path: ./test-results
        - name: Run Chromatic
          uses: chromaui/action@latest
          with:
            playwright: true
            projectToken: ${{ secrets.CHROMATIC_PLAYWRIGHT }}
            exitOnceUploaded: true
            configFile: '.chromatic.playwright.config.json'
          env:
            CHROMATIC_ARCHIVE_LOCATION: ./test-results
