name: 'E2e Tests'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - final

jobs:
  component-tests:
    runs-on: ubuntu-latest
    name: 'E2e Tests'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - uses: volta-cli/action@v4
      - name: Install Dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test:e2e
      - name: Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_STORYBOOK }}
          configFile: '.chromatic.config.json'
